"""creating all tempekan

Revision ID: 654c58876870
Revises: 44f375fd6724
Create Date: 2021-07-15 00:11:53.331278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654c58876870'
down_revision = '44f375fd6724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tempekan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Tempekan', sa.Integer(), nullable=True),
    sa.Column('NamaLengkap', sa.Text(), nullable=True),
    sa.Column('NamaPangillan', sa.Text(), nullable=True),
    sa.Column('TempatLahir', sa.Text(), nullable=True),
    sa.Column('TanggalLahir', sa.Integer(), nullable=True),
    sa.Column('Umur', sa.Integer(), nullable=True),
    sa.Column('Nik', sa.Integer(), nullable=True),
    sa.Column('Alamat', sa.Text(), nullable=True),
    sa.Column('NoHp', sa.Integer(), nullable=True),
    sa.Column('Email', sa.Text(), nullable=True),
    sa.Column('Bakat', sa.Text(), nullable=True),
    sa.Column('NamaOrtu', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tempekan')
    # ### end Alembic commands ###
